Hospital_Management_System/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('patients/',include('patients.urls'))
]

app1/urls.py
from django.urls import path
from.import views
app_name="firstapp"
urlpatterns=[
    path('login/',views.getloginpage,name="login_user"),
    path('login_master',views.getmasterpage,name="master"),
    path('changepassword',views.getchangepassword,name="changepassword"),
    path('settings',views.getsettingspage,name="settings"),
    path('profile',views.getprofilepage,name="profile")
]

patients/urls.py
from django.urls import path
from . import views
app_name="patient"

urlpatterns=[
    path('patients/',views.getregistrationpage,name="patient_reg"),
    path('patients_profile',views.getprofilepage,name="profile")
]

app1/models.py
from django.db import models

# Create your models here.

patients/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def getloginpage(request):
    return render(request,'login.html')

def getmasterpage(request):
    return render(request,'master.html')  

def getchangepassword(request):
    return render(request,'changepassword.html')

def getsettingspage(request):
    return render(request,'settings.html')

def getprofilepage(request):
    return render(request,'profile.html')
  

patients/views.py
from django.shortcuts import render

# Create your views here.
def getregistrationpage(request):
    return render(request,'patient_registration.html')

def getprofilepage(request):
    return render(request,'patient_profile.html')    

app1/templates/changepassword.html
{% extends 'master.html' %}
{% block content %}
<h1>changepassword</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur saepe quidem quae expedita ad inventore eos, facilis odio tenetur voluptatibus repudiandae perferendis sed doloribus non aperiam, quis consequuntur corporis vel.</p>
{% endblock %}

app1/templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        /* #name{
            border-color: aqua;
        } */

        /* .text{
            border-color: aqua;
        } */
        input{
            border-color: brown;
        }
    </style>
</head>
<body>
    <h1>new project in github</h1>
    <!-- inline css -->
    <p style="background-color: blue;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur vero nulla corrupti optio fuga totam id repellendus, officia dicta saepe in ex odio magnam suscipit nisi repellat, at est sunt!</p>
    <!-- internal css -->
    <input type="text" name="" id="name" class="text">
</body>
</html>

app1/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hospital Management system</h1>
    <form>
        <label>username</label>
        <input type="text" name="" id=""><br><br>
        <label>password</label>
        <input type="password" name="" id=""><br><br>
        <button>login</button>  
    </form>
    <img src="{% static 'images/wp11070598-imac-4k-wallpapers.jpg' %}" alt="" height="200" width="200">
    <a href="">register</a>
    
</body>
</html>

app1/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="height: 600px; width: 200px; border: 1px solid; float: left;"
        <ul>
            <li><a href="{% url 'firstapp:profile' %}">profile</a></li>
            <li><a href="{% url 'firstapp:changepassword' %}">change password</a></li>
            <li><a href="{% url 'firstapp:settings' %}">settings</a></li>
        </ul>
    </div>

    <div style="height: 600px; width: 900px; border: 1px solid; float: left;">
        {% block content%}
    
        {% endblock %}
    </div>
    
</body>
</html>

app1/templates/profile.html
{% extends 'master.html' %}
{% block content %}
<h1>profile</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis soluta vel hic autem facere doloribus veniam sed. Eaque sapiente inventore provident voluptatem adipisci illo quisquam. Quaerat iure pariatur molestiae dolorum?</p>
{% endblock %}

app1/templates/settings.html
{% extends 'master.html' %}
{% block content%}
<h1>settings</h1>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum inventore, porro impedit molestias aperiam rem aut temporibus cum, dolorem maiores officia fuga tempore voluptates hic quibusdam sunt laudantium adipisci explicabo.</p>
    
{% endblock %}

patients/templates/patient_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>patient</h1>
    <form>
        <label>name</label>
        <input type="text" name="" id=""><br><br>
        <label>age</label>
        <input type="number" name="" id=""><br><br>
    </form>
</body>
</html>

patients/templates/patients_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>name</h1>
    <h2>address</h2>
    <h3>age</h3>
</body>
</html>